import Document, { Html, Head, Main, NextScript } from 'next/document';

class MyDocument extends Document {
	static async getInitialProps(ctx) {
		const initialProps = await Document.getInitialProps(ctx);
		return { ...initialProps };
	}
	render() {
		return (
			<Html lang="en">
				<Head>
					<title>Lynxai</title>
					<meta charSet="UTF-8" />
					<meta name="description" content="Generated by create next app" />
					<link rel="icon" href="/favicon.ico" />
					{/* <link href="http://fonts.cdnfonts.com/css/futura-md-bt" rel="stylesheet" /> */}
					{/* <link href="http://fonts.cdnfonts.com/css/souvenir" rel="stylesheet" /> */}
					<meta name="viewport" content="width=device-width, initial-scale=1.0" />
				</Head>
				<body>
					<Main />
					<NextScript />
				</body>
			</Html>
		);
	}
}

export default MyDocument;
