import Head from 'next/head';
import ChooseUs from '../components/chooseUs/chooseUs';
import DemoSection from '../components/DemoSection/demo';
import HeroSection from '../components/heroSection/hero';
import ManageSection from '../components/manageSection/manage';
import OurProduct from '../components/ourProduct/product';
export default function Home() {
	return (
		<div>
			<Head>
				<title>Lynxai</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<HeroSection />
			<div className="arrow-gif-con">
				<img className="arrow-gif" src="./images/arrow.gif" />
			</div>
			<ManageSection />
			<div className="arrow-gif-con">
				<img className="arrow-gif" src="./images/arrow.gif" />
			</div>
			<OurProduct />
			<div className="arrow-gif-con">
				<img className="arrow-gif" src="./images/arrow.gif" />
			</div>
			<ChooseUs />
			<div className="arrow-gif-con">
				<img className="arrow-gif" src="./images/arrow.gif" />
			</div>
			<DemoSection />
		</div>
	);
}
